### ISSUE TITLE
邵志远老师 多核操作系统实践 教案

### ISSUE THREAD

**Issue by zijeric** [shishujuan/mit6.828-2017#1]
请问可以提供一下邵志远老师多核操作系统实践的教案吗？老师的主页找不到了，谢谢

**Comment by shishujuan** [comment]
不好意思，才看到。发附件了，请查收。


| |
ssj
|
|
ssjhust@163.com
|
签名由网易邮箱大师定制


在2021年02月12日 01:58，A1va<notifications@github.com> 写道：

请问可以提供一下邵志远老师多核操作系统实践的教案吗？老师的主页找不到了，谢谢

**Comment by A1va** [comment]
> 请问可以提供一下邵志远老师多核操作系统实践的教案吗？老师的主页找不到了，谢谢
